apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-url-shortener-app
  labels:
    app: go-url-shortener-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-url-shortener-app
  template:
    metadata:
      labels:
        app: go-url-shortener-app
    spec:
      containers:
        - name: go-url-shortener-app
          image: leonardom/go-url-shortener-app
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8000
          env:
            - name: DB_TYPE
              value: redis
            - name: REDIS_URL              
              value: redis://go-url-shortener-redis-service:6379

---
apiVersion: v1
kind: Service
metadata:
  name: go-url-shortener-app-service
spec:
  type: NodePort
  selector:
    app: go-url-shortener-app
  ports:
    - port: 8000
      targetPort: http
      nodePort: 30510
      protocol: TCP
