apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-url-shortener-redis
  labels:
    app: go-url-shortener-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-url-shortener-redis
  template:
    metadata:
      labels:
        app: go-url-shortener-redis
    spec:
      containers:
        - name: redis
          image: redis:4
          command: ["redis-server"]
          args: ["--appendonly", "yes"]
          ports:
             - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: go-url-shortener-redis-service
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    app: go-url-shortener-redis
