apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-albums-app
  labels:
    app: go-albums-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-albums-app
  template:
    metadata:
      labels:
        app: go-albums-app
    spec:
      containers:
        - name: go-albums-app
          image: leonardom/go-albums-app
          imagePullPolicy: Never
          ports:
            - name: http
              containerPort: 8001
          env:
            - name: PORT
              value: "8001"
            - name: DB_HOST
              value: "go-albums-myql-service"
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              value: "devdb"
            - name: DB_USER
              value: "devdbuser"
            - name: DB_PASS
              value: "devdbpwd"
---
apiVersion: v1
kind: Service
metadata:
  name: go-albums-app-service
spec:
  type: NodePort
  selector:
    app: go-albums-app
  ports:
    - port: 8001
      targetPort: http
      nodePort: 30511
      protocol: TCP
